"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q4js*g3v^gw+)k+$hti&4(j7rj$0pql+_1@=85amb0o0*6&@!m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cron',
    'account',    
    'Ecom',
    'MBmovies',
    # 'MBtheatersAndBooking',
    'MusicStreaming',

    'rest_framework',
    'rest_framework_simplejwt',

    'MBtheatersAndBooking.apps.YourAppConfig',
]

# CRON_CLASSES = [
#     'your_app.tasks.MonthlyAnalyticsJob',
# ]

CRON_CLASSES = [
    'MusicStreaming.tasks.MonthlyAnalyticsJob',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Change this to the database engine you are using
        'NAME': 'uka_master_db',
        'USER': 'root',
        'PASSWORD': 'AmanRoot2004',
        'HOST': 'localhost',
        'PORT': '3306',  # Change this to the port your database is running on
    }
}

AUTH_USER_MODEL ='account.User'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


from datetime import timedelta 

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=20),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=120),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

REST_FRAMEWORK = {
    
    'DEFAULT_AUTHENTICATION_CLASSES': (
        
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
    
}


API_KEY = "3d739b9e-ab26-11ee-8cbb-0200cd936042" #"f52019e2-aa6b-11ee-8cbb-0200cd936042"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'thetoxtal@gmail.com'
EMAIL_HOST_PASSWORD = 'aashuQT0530'



# Product Images
PRODUCT_MEDIA_URL = '/media/product/'
PRODUCT_MEDIA_ROOT = BASE_DIR / "media/product"

# Profile Images
PROFILE_MEDIA_URL = '/media/profile/'
PROFILE_MEDIA_ROOT = BASE_DIR / "media/profile"

# Movie Images
MOVIESIMGS_MEDIA_URL = '/media/movieIMGs/'
MOVIESIMGS_MEDIA_ROOT = BASE_DIR / "media/movieIMGs"

# Movie Director Images
MOVIESDIRECTORSIMGS_MEDIA_URL = '/media/DirectorIMGs/'
MOVIESDIRECTORSIMGS_MEDIA_ROOT = BASE_DIR / "media/DirectorIMGs"

# Movie Producer Images
MOVIESPRODUCERIMGS_MEDIA_URL = '/media/ProducerIMGs/'
MOVIESPRODUCERIMGS_MEDIA_ROOT = BASE_DIR / "media/ProducerIMGs"

# Movie Cast Images
MOVIESCASTIMGS_MEDIA_URL = '/media/CastIMGs/'
MOVIESCASTIMGS_MEDIA_ROOT = BASE_DIR / "media/CastIMGs"

# Movie Genre Images
MOVIESGENREIMGS_MEDIA_URL = '/media/GenreIMGs/'
MOVIESGENREIMGS_MEDIA_ROOT = BASE_DIR / "media/GenreIMGs"

# Movie Language Images
MOVIESLANGUAGEIMGS_MEDIA_URL = '/media/LanguageIMGs/'
MOVIESLANGUAGEIMGS_MEDIA_ROOT = BASE_DIR / "media/LanguageIMGs"

# Music Audio
MUSICAUDIO_MEDIA_URL = '/media/MusicAudio/'
MUSICAUDIO_MEDIA_ROOT = BASE_DIR / "media/MusicAudio"

# Music Cover Img
MUSICCOVERIMGS_MEDIA_URL = '/media/MusicCoverIMGs/'
MUSICCOVERIMGS_MEDIA_ROOT = BASE_DIR / "media/MusicCoverIMGs"