# Generated by Django 5.0 on 2024-02-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBmovies', '0005_movie_type_m_movie_type'),
        ('MBtheatersAndBooking', '0018_showtime_m_m_language_showtime_m_m_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater_m',
            name='City_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m'),
        ),
    ]
