# Generated by Django 5.0 on 2024-02-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBmovies', '0005_movie_type_m_movie_type'),
        ('MBtheatersAndBooking', '0019_theater_m_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater_m',
            name='City_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MBmovies.movie_m'),
        ),
    ]
