# Generated by Django 5.0 on 2024-02-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0021_alter_theater_m_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater_m',
            name='City_ID',
        ),
    ]
