# Generated by Django 5.0 on 2024-02-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBtheatersAndBooking', '0022_remove_theater_m_city_id'),
        ('account', '0003_remove_address_address_address_house_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater_m',
            name='City_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.city'),
        ),
    ]
